### ISSUE TITLE
Bug: Raw Query Group By

### ISSUE THREAD

**Issue by t3ndai** [vapor/fluent-provider#31]
Using a raw Query with Fluent I get wrong numbers from my query
```swift
guard let majorSet = try? Job.database?.raw("select major, avg(pay) as average from jobs group by major order by average desc").converted(to: JSON.self).makeResponse() else { throw SQL.serialization }
```
I get the following Response which is wrong: 

[
  {
    "major": "Product Design",
    "average": "0.000000116400"
  },
  {
    "major": "Software Engineering",
    "average": "0.000000000009"
  },
  {
    "major": "Computer Science",
    "average": "0.000000082500"
  },
  {
    "major": "Computer Engineering",
    "average": "0.000000065000"
  },
  {
    "major": "Chemical Engineering",
    "average": "0.000000058224"
  },
  {
    "major": "Accounting",
    "average": "0.000000055000"
  },
  {
    "major": "Information Technology",
    "average": "0.000000054000"
  },
  {
    "major": "Marketing",
    "average": "0.000000036000"
  }
]

As those values should be whole numbers

**Comment by vzsg** [comment]
You really should have opened this in one of the postgresql repos.
Including the source of the Job class would have been nice.

Let's continue in vapor-community/postgresql#47.
